[package]
name = "rgapi-py"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
test = false

[dependencies]
rgapi = { path = ".." }
grep-matcher.workspace = true
pyo3 = { version = ">=0.29", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.29"
